declare module "@lucide/astro" {
	import type { LucideProps } from "lucide-react";
	export type Icon = (props: LucideProps) => any;
	export const ArrowLeft: Icon;
	export const ArrowRight: Icon;
	export const Check: Icon;
	export const ChevronRight: Icon;
	export const Mail: Icon;
	export const MapPin: Icon;
	export const Phone: Icon;
	export const ExternalLink: Icon;
	export const Github: Icon;
	export const Linkedin: Icon;
	export const Twitter: Icon;
	export const Instagram: Icon;
	export const Menu: Icon;
	export const X: Icon;
	export const Calendar: Icon;
	export const Clock: Icon;
	export const User: Icon;
	export const Tag: Icon;
	export const Search: Icon;
	export const Globe: Icon;
	export const Code: Icon;
	export const Laptop: Icon;
	export const Smartphone: Icon;
	export const Layout: Icon;
	export const Database: Icon;
	export const Zap: Icon;
	export const Shield: Icon;
	export const Star: Icon;
	export const Heart: Icon;
	export const MessageSquare: Icon;
	export const Send: Icon;
	export const Copy: Icon;
	export const Download: Icon;
	export const Share2: Icon;
	export const MoreHorizontal: Icon;
	export const MoreVertical: Icon;
	// Navigation & actions
	export const ArrowUpRight: Icon;
	export const ArrowUp: Icon;
	export const ChevronDown: Icon;
	export const ChevronLeft: Icon;
	// Status & feedback
	export const CircleCheck: Icon;
	export const CircleX: Icon;
	export const CircleDollarSign: Icon;
	// Trust & security
	export const ShieldCheck: Icon;
	export const BadgeCheck: Icon;
	export const FileCheck: Icon;
	export const Lock: Icon;
	export const LockKeyhole: Icon;
	// Business & work
	export const Award: Icon;
	export const Briefcase: Icon;
	export const BriefcaseBusiness: Icon;
	export const Building2: Icon;
	export const Users: Icon;
	export const UserRound: Icon;
	// Productivity & tech
	export const Rocket: Icon;
	export const Sparkles: Icon;
	export const Cpu: Icon;
	export const Terminal: Icon;
	export const Timer: Icon;
	// Commerce & services
	export const Store: Icon;
	export const Utensils: Icon;
	export const Scissors: Icon;
	export const Dumbbell: Icon;
	export const HeartPulse: Icon;
	export const Headphones: Icon;
	export const CalendarCheck: Icon;
	export const MonitorSmartphone: Icon;
	export const FileText: Icon;
	export const Palette: Icon;
}
